### PR TITLE
WIP: work on proxy

### PR DESCRIPTION
**Pull request by Jollyfant**
If anyone wants to help me with the design of the proxy described by @kaestli in #75. I took the NOA example and added a Dockerifle that runs Apache and enables the example `.conf` file.

I don't really know how to proceed. I configured `eida.gein.noa.gr` in `/etc/hosts` to points to localhost but it doesn't really do anything besides an `Internal Server Error`.

### CODE REVIEW

**Comment by damb** [comment]
Ciao @Jollyfant,

In order to make profit of the setup described in #75, firstly `eida-federator` must implement the HTTP GET endpoint requests as described in #77. Besides, the bulk requests (implemented with 11313cc9b23534e12901e6727e0dd458e17c858e) and the reverse proxy caching setup are somehow mutual exclusive since caching most probably will work best with granular endpoint requests. 

Though, implementing #75 for our docker setup might already be worth it. When doing so, also check if there is a way of exclusively relying on the endpoints DNS instead of using hard coded IPs.

**Comment by kaestli** [comment]
note that you can set up this configuration anyway. If done correctly, it would proxy also POST requests, however (in agreement with rfc 2616) not cache them.

**Comment by Jollyfant** [comment]
> do you have the http 500 only with station requests to NOA or also with dataselect requests?

It was both but it turns out I had to enable `a2enmod proxy_http` too to make it work. A request to `eida.gein.noa.gr` now goes through localhost and data is returned. However, when I retry the same request it doesn't seem go to faster.

**Comment by Jollyfant** [comment]
root@0498e3397b2f:/tmp# curl "eida.gein.noa.gr/fdsnws/station/1/query?start=2019-01-01&end=2019-01-01T00:01:00&level=response" > /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 19.1M    0 19.1M    0     0  1695k      0 --:--:--  0:00:11 --:--:-- 2744k
    root@0498e3397b2f:/tmp# curl "eida.gein.noa.gr/fdsnws/station/1/query?start=2019-01-01&end=2019-01-01T00:01:00&level=response" > /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 19.1M    0 19.1M    0     0  1570k      0 --:--:--  0:00:12 --:--:-- 2679k
    root@0498e3397b2f:/tmp# curl "eida.gein.noa.gr/fdsnws/station/1/query?start=2019-01-01&end=2019-01-01T00:01:00&level=response" > /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 19.1M    0 19.1M    0     0  1697k      0 --:--:--  0:00:11 --:--:-- 2826k

**Comment by damb** [comment]
Implemented with #85.

**Pull request closed without merging**
